### ISSUE TITLE
Issue with ros file

### ISSUE THREAD

**Issue by dfrenz3** [rweyrauch/PrettyScribe#14]
When using a .ros file vs a rosz file it will interpret the file differently as the uncompressed file uses a Unicode character not an ASCII version as such it will show nonsense characters. 
![prettyscribe issue 3](https://user-images.githubusercontent.com/83209487/126242147-29497499-35f1-4d2d-b1f6-c7c70244adc0.PNG)
![prettyscribe issue 4](https://user-images.githubusercontent.com/83209487/126242148-88f4f6b2-30f6-41a1-9e2f-a3a933263f2b.PNG)

**Comment by mardanbeigi** [comment]
I can still repro this. The problem is app.ts uses `FileReader.readAsBinaryString` to handle the zip case, but doesn't convert to UTF8 if the input file is unzipped. `readAsBinaryString` is deprecated, so we'll want to switch to ArrayBuffers anyway, and can use the newer `blob.arrayBuffer()` method and covert to UTF8 using `TextDecoder`

I'll make the changes in the next week

**Comment by rweyrauch** [comment]
Excellent.  This has been a long standing big.
